spring.datasource.url=jdbc:postgresql://db.TU_PROYECTO.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=TU_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect